### ISSUE TITLE
Snippets in PHP

### ISSUE THREAD

**Issue by JackCimberly** [suvamrox/vscode-w3.css-plugin#1]
Hello SuvamRox.

Thank you for your extension.

If I now edit a PHP file (PHP mode -> bottom right), the Visual Studio code does not suggest anything about W3.
Only when I switch to HTML (bottom right).

Can you modify it so that it also works in PHP mode?

Thanks very much.

Regards
JackCimberly

**Comment by JackCimberly** [comment]
`{
				"language": "php",
				"path": "./snippets/snippets.code-snippets"
			},`

Not working with PHP (php)

Thanks.

JackCimberly

**Comment by suvamrox** [comment]
@JackCimberly 
sorry for late reply. php language support is already added. please change your vs code Quick suggestions setting. 
 "editor.quickSuggestions": {
        "other": "on",
        "comments": "off",
        "strings": true
    }
https://www.youtube.com/watch?v=aFQFxektD-M
